config/routes.rb
Mosh2::Application.routes.draw do
  resources :settings do
    put "toggle"
  end

  namespace :admin do
    resources :users
  end

  resources :poster_statuses

  resources :posters do
    put "finish", "pend", "print"
  end

  resources :job_statuses

  resources :jobs do
    put "finish", "pend", "finalize"
    resources :posters
  end

  resources :work_orders
  resources :order_statuses
  resources :after_hours_accesses
  resources :semesters
  resources :terms

  resources :locations do
    resources :workstations, only: [:index, :new, :create]
  end

  resources :location_types
  resources :hardwares, except: [:new, :create]
  resources :hardware_statuses
  resources :hardware_types

  resources :workstations, except: [:new, :create] do
    resources :hardwares, only: [:index, :new, :create]
  end

  resources :workstation_types
  resources :hours
  resources :lab_overview, only: :index
  resources :inventory, only: :index

  namespace :api do
    namespace :v1 do
      resources :labs, only: [:index, :show] do
        resources :workstations, only: :index
      end
      resources :workstations, only: :show do
        resources :hardwares, only: [:index, :new, :create]
      end
      resources :hardwares, only: :show
    end
  end

  devise_for :users

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root to: 'home#index'
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id            :integer          not null, primary key
#  user_id       :integer
#  due_date      :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  job_status_id :integer
#

class Job < ActiveRecord::Base
  attr_accessible :due_date, :user_id, :job_status_id, :finalize, :denial
  has_one :poster_overview
  has_many :posters, :dependent => :destroy
  belongs_to :user, :class_name => "User", :foreign_key => :user_id
  belongs_to :job_status
  has_paper_trail

  validate :check_date, if: :should_validate_date?

  def format_date
    self.due_date.strftime('%m/%d/%Y')
  end
  def check_date
    if due_date.present? && due_date < Date.today
      errors.add(:due_date, "Posters cannot be due before today!")
    end
  end
  def should_validate_date?
   new_record? || due_date_changed?
  end
  def set_pending
    self.job_status = JobStatus.where(name: "Pending").first
  end
  def set_finished
    self.job_status = JobStatus.where(name: "Finished").first
  end
  def set_denied
    self.job_status = JobStatus.where(name: "Denied").first
  end
  def set_finalize
    self.finalize = true
  end
  def get_mounting
    mount = false
    self.posters.each do |poster|
      if poster.mounting
        mount = true
      end
    end
    mount
  end
  def self.search(search)
    if search
      joins(:user).where('email LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!
  helper_method :sort_column, :sort_direction

  # GET /jobs
  # GET /jobs.json
  def index

    @per_page = params[:per_page] || 25
    if !current_user.management
      @jobs = Job.where(user_id: current_user.id)
                .search(params[:search])
                .order(sort_column + " " + sort_direction)
                .paginate(:per_page => @per_page, :page => params[:page])
      @isManagement = false
    else
      @jobs = Job.search(params[:search])
                .order("#{sort_column} #{sort_direction}")
                .paginate(:per_page => @per_page, :page => params[:page])
      @isManagement = true
    end
    @job_statuses = JobStatus.all

    if params[:job_status]
      @job_status = JobStatus.find(params[:job_status])
      if !current_user.management
        @jobs = @job_status.jobs.where(user_id: current_user.id)
                          .order(sort_column + " " + sort_direction)
                          .paginate(:per_page =>@per_page, :page => params[:page])
      else
        @jobs = @job_status.jobs.order(sort_column + " " + sort_direction)
                          .paginate(:per_page =>@per_page, :page => params[:page])
      end
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    if authorized_user?(current_user, @job)
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @job }
      end
    else
      render file: "#{Rails.root}/public/404.html", status: 404, layout: false
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])
    if !params[:job][:user_id]
      @user = current_user
      @job.user_id = @user.id
    else
      @user = User.find(params[:job][:user_id])
    end
    @job.set_pending
    @job.due_date = DateTime.strptime(params[:job][:due_date], '%m/%d/%Y').to_date
    @job.finalize = false;

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])
    if params[:job][:due_date]
      params[:job][:due_date] = DateTime.strptime(params[:job][:due_date], '%m/%d/%Y').to_date
      puts params[:job][:due_date]
    end
    if params[:job][:denial]
      puts 'in denial block'
      @job.set_denied
    end

    respond_to do |format|
      if @job.update_attributes(params[:job])
        if @job.denial
          PosterMailer.job_denial(@job.id, current_user.id, @job.denial).deliver
        end
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def finalize
    @job = Job.find(params[:job_id])
    @job.set_finalize

    if @job.save
      @date = @job.format_date
      @posters = @job.posters
      PosterMailer.new_job(@job.id, current_user.id, @date, @posters, @job.get_mounting).deliver
      PosterMailer.new_job_alert(@job.user.id, @date, @job.id).deliver

      redirect_to @job, notice: 'Your job was finalized.'
    else
      redirect_to @job, notice: 'Your job could not be finalized.'
    end
  end

  def finish
    @job = Job.find(params[:job_id])
    @job.set_finished

    if @job.save
      PosterMailer.job_finished(@job.id, @job.user.id).deliver
      PosterMailer.job_finished_alert(@job.id, @job.user.id).deliver
      redirect_to @job, notice: 'Job was successfully finished.'
    else
      redirect_to @job, notice: 'Job could not be finished.'
    end
  end

  def pend
    @job = Job.find(params[:job_id])
    @job.set_pending
    @job.denial = nil

    if @job.save
      redirect_to @job, notice: 'Job is pending.'
    else
      redirect_to @job, notice: 'Job could not be pended.'
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private
  def sort_column
    Job.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def authorized_user?(user, job)
    user == job.user || user.management
  end

  def set_number_of_entries_per_page(number)

  end
end

app/helpers/jobs_helper.rb
module JobsHelper

  def get_finalized(finalize)
    if finalize
      "<span class='label label-success'>Ok!</span>".html_safe
    else
      "<span class='label label-important'>Not Finalized</span>".html_safe
    end
  end

  def all_finished(posters)
    posters.map { |p| p.poster_status.name == "Finished" }.reduce{ |a, b| a && b }
  end

  def check_date(due_date)
    due_date < DateTime.now + 2.days
  end

  def get_queue(job)
    if job.job_status.name != "Pending"
      "n/a"
    else
      count = 0
      jobs = JobStatus.where(name: "Pending").first.jobs.where("id < ?", job.id)

      jobs.each do |j|
        count += j.posters.count
      end
      count
    end
  end
end

app/views/jobs/_deny_job_modal.html.erb
<div class="modal hide denyModal" id="denyJobModal">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h3>Why was this job denied?</h3>
  </div>
  <div class="modal-body">
    <%= form_for @job, method: :put do |f| %>
      <div class="row">
        <div class="span5">
          <%= f.text_area :denial, class: 'denial-reason' %>
        </div>
      </div>
      <div class="row">
        <div class="span4">
          <%= f.submit 'Deny Job', class: 'btn btn-large btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/jobs/_form.html.erb
<%= simple_form_for(@job, html: { class: 'form-horizontal' }) do |f| %>

  <div class="form-inputs">
    <% if current_user.management %>
      <%= f.association :user %>
    <% end %>
    <%= f.input :due_date, as: :string, input_html: { data: { behavior: 'datepicker' } }, hint: 'Note: Jobs requested within 48 business hours of due date are not guaranteed.' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/jobs/_jobs.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="table table-bordered table-striped">
  <tr>
    <!-- <th>Job ID</th> -->
    <th><%= sortable "id", "Job ID" %></th>
    <!-- <th>User</th> -->
    <th>User</th>
    <!-- <th>Created at</th> -->
    <th><%= sortable "created_at", "Created at" %></th>
    <!-- <th>Due date</th> -->
    <th><%= sortable "due_date", "Due Date" %></th>
    <th># Posters</th>
    <th>Status</th>
    <th>Finalized?</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>

  <% @jobs.each do |job| %>
    <tr>
      <td><%= link_to job.id, job %></td>
      <td><%= job.user.email if job.user %></td>
      <td><%= format_date(job.created_at) %></td>
      <td><%= format_date(job.due_date) if job.due_date %></td>
      <td><%= job.posters.count %></td>
      <td><%= show_status(job.job_status.name) %></td>
      <td><%= get_finalized(job.finalize) %></td>
      <td>
        <%= link_to edit_job_path(job) do %>
          <i class="fa fa-edit"></i>
        <% end %>
      </td>
      <td>
        <%= link_to job, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <i class="fa fa-trash-o"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<%= will_paginate @jobs %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h2>View Poster Jobs</h2>
<div class="row">
  <div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="#">Job</a>
    <ul class="nav">
      <% if @isManagement %>
        <li>
          <!-- <div class="span1"> -->
            <%= form_tag(jobs_path, method: 'get', id: "jobs_search", class: "navbar-search pull-left") do %>
              <%= text_field_tag :search, params[:search], :class => "search-query"%>
          <!-- </div> -->
        </li>
        <li>
          <!-- <div class="span1"> -->
              <%= submit_tag "Search", name: nil, class: 'btn btn-block btn-medium btn-info'%>
            <% end %>
          <!-- </div> -->
        </li>
      <% end %>
      <li>
        <%= form_tag(jobs_path, method: 'get', class: 'navbar-form form-inline', id: 'status_form') do %>
          <%= select_tag('job_status', options_from_collection_for_select(@job_statuses, :id, :name), :prompt => "Filter by Status", :onchange => "this.form.submit();")%>
          <% end %>
      </li>
      <li>
        <div class="pull-left">
          <%= form_tag(jobs_path, method: 'get', class: 'navbar-form form-inline', id: 'status_form') do %>
            <%= select_tag :per_page, options_for_select([5,10,20,25,50], params[:per_page].to_i),  :prompt => "Items Per Page",
       :onchange => "if(this.value){window.location='?per_page='+this.value;}" %>
          <%end %>
        </div>
      </li>
      <li >
        <div class="pull-left">
          <%= link_to new_job_path, class: "btn btn-block btn-medium btn-success" do %>
            <i class="fa fa-plus"></i> Create a New Job
          <% end %>
        </div>
      </li>
    </ul>
  </div>
  </div>
  <!-- <h5><%= @job_status.name if @job_status %> Jobs:</h5> -->
</div>

<div class="row">
  <div id='jobs'>
    <%= render :partial => 'jobs'%>
  </div>
</div>

app/views/jobs/index.js.erb
$("#jobs").html("<%= escape_javascript(render("jobs")) %>");

app/views/jobs/new.html.erb
<%= render 'shared/progress', page: 'create' %>

<h1>Create a New Job</h1>

<%= render 'form' %>

<div class="modal" id="warningModal">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">x</button>
    <h3>Notice</h3>
  </div>
  <div class="modal-body">
    <p>Poster jobs submitted within 48 business hours of due date are not guaranteed!</p>
  </div>
  <div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn btn-medium btn-info">Close</button>
  </div>
</div>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<%= render 'shared/progress', page: 'review' %>
<%= render 'deny_job_modal' %>
<h2>Poster Job Details</h2>

<% if !@job.finalize %>
  <p class="text-center">Once you are finished adding posters to your job, make sure to click the "Finalize Job" button to finalize your order.</p>
  <br><% end %>

<div class="row job-actions">
  <div class="span3 offset3">
    <%= link_to 'Add Poster to Job', new_job_poster_path(@job), class: 'btn btn-block btn-large btn-primary' unless @job.finalize %>
  </div>
  <div class="span3">
    <%= link_to 'Finalize Job', job_finalize_path(@job), method: :put, class: 'btn btn-large btn-block btn-success' unless @job.finalize %>
  </div>
</div>

<div class="row job-actions">
  <% if current_user.management %>
    <% if @job.job_status.name == "Pending" %>
      <div class="span3 offset3">
        <% if all_finished(@job.posters) %>
          <%= link_to job_finish_path(@job), method: :put, class: 'btn btn-medium btn-block btn-info' do %>
            <i class="fa fa-cogs"></i> Finish Job
          <% end %>
        <% end %>
      </div>
      <div class="span3">
        <a data-toggle="modal" href="#denyJobModal" class="btn btn-medium btn-block btn-danger"><i class="fa fa-cogs"></i> Deny Job</a>
      </div>
    <% else %>
      <div class="span3 offset3">
        <%= link_to job_pend_path(@job), method: :put, class: 'btn btn-block btn-medium btn-warning' do %>
          <i class="fa fa-cogs"></i> Pend Job
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

<div class="row">
  <div class="span6 offset3">
    <table class="table table-bordered">
      <tr>
        <th>Job ID:</th>
        <td><%= @job.id %></td>
      </tr>
      <tr>
        <th>User:</th>
        <td><%= @job.user.email %></td>
      </tr>
      <tr>
        <th>Created at:</th>
        <td><%= format_date(@job.created_at) %></td>
      </tr>
      <tr>
        <th>Due date:</th>
        <td><%= format_date(@job.due_date) if @job.due_date %></td>
      </tr>
      <tr>
        <th>Posters:</th>
        <td>
          <% @job.posters.each do |poster| %>
            <%= show_status(poster.poster_status.name) %>  <%= link_to poster.name, poster, target: "_blank" %><br>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>Job status:</th>
        <td><%= show_status(@job.job_status.name) %></td>
      </tr>
      <tr>
        <th>Your number in the queue:</th>
        <td><%= get_queue(@job) %></td>
      </tr>
    </table>

    <div clas="span6">
      <%= link_to 'Finalize Job', job_finalize_path(@job), method: :put, class: 'btn btn-large btn-block btn-success' unless @job.finalize %>
     <br>
      <%= button_to "Delete Poster Job", @job, method: :delete, class: 'btn btn-block btn-medium btn-danger', data: { confirm: 'Are you sure? This cannot be undone.' } %>
    </div>
    <%= link_to 'Edit Job', edit_job_path(@job) %> | <%= link_to 'Back', jobs_path %>
  </div>
</div>