config/routes.rb
Mosh2::Application.routes.draw do
  resources :settings do
    put "toggle"
  end

  namespace :admin do
    resources :users
  end

  resources :poster_statuses

  resources :posters do
    put "finish", "pend", "print"
  end

  resources :job_statuses

  resources :jobs do
    put "finish", "pend", "finalize"
    resources :posters
  end

  resources :work_orders
  resources :order_statuses
  resources :after_hours_accesses
  resources :semesters
  resources :terms

  resources :locations do
    resources :workstations, only: [:index, :new, :create]
  end

  resources :location_types
  resources :hardwares, except: [:new, :create]
  resources :hardware_statuses
  resources :hardware_types

  resources :workstations, except: [:new, :create] do
    resources :hardwares, only: [:index, :new, :create]
  end

  resources :workstation_types
  resources :hours
  resources :lab_overview, only: :index
  resources :inventory, only: :index

  namespace :api do
    namespace :v1 do
      resources :labs, only: [:index, :show] do
        resources :workstations, only: :index
      end
      resources :workstations, only: :show do
        resources :hardwares, only: [:index, :new, :create]
      end
      resources :hardwares, only: :show
    end
  end

  devise_for :users

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root to: 'home#index'
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :name, :set, :description

  def toggle_set
    if self.set
      self.set = false
    else
      self.set = true
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  require "#{Rails.root}/lib/mosh_modules/admin_module"
  include MoshModules::AdminModule
  before_filter :admin_filter

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @settings }
    end
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
    @setting = Setting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/new
  # GET /settings/new.json
  def new
    @setting = Setting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/1/edit
  def edit
    @setting = Setting.find(params[:id])
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(params[:setting])

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render json: @setting, status: :created, location: @setting }
      else
        format.html { render action: "new" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /settings/1
  # PUT /settings/1.json
  def update
    @setting = Setting.find(params[:id])

    respond_to do |format|
      if @setting.update_attributes(params[:setting])
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting = Setting.find(params[:id])
    @setting.destroy

    respond_to do |format|
      format.html { redirect_to settings_url }
      format.json { head :no_content }
    end
  end

  def toggle
    @setting = Setting.find(params[:setting_id])
    @setting.toggle_set

    if @setting.save
      redirect_to settings_url, notice: 'Setting was changed.'
    else
      redirect_to settings_url, notice: 'Setting could not be changed.'
    end
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
  def get_on_off(set)
    if set
      "On"
    else
      "Off"
    end
  end

  def turn_on_off(set)
    if set
      "Turn Off"
    else
      "Turn On"
    end
  end

  def get_button(set)
    if set
      'btn btn-danger'
    else
      'btn btn-success'
    end
  end
end

app/views/settings/_form.html.erb
<%= simple_form_for(@setting, html: { class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :set %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.submit 'Submit Setting', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<h2>Settings</h2>

<table class="table">
  <tr>
    <th>Current Setting</th>
    <th>Change Setting</th>
    <th>Name</th>
    <th>Description</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

  <% @settings.each do |setting| %>
    <tr>
      <td><%= get_on_off(setting.set) %>
      <td><%= link_to turn_on_off(setting.set), setting_toggle_path(setting), class: get_button(setting.set), method: 'put' %></td>
      <td><%= link_to setting.name, setting %></td>
      <td><%= setting.description %></td>
      <td>
        <%= link_to edit_setting_path(setting) do %>
          <i class="fa fa-edit"></i>
        <% end %>
      </td>
      <td>
        <%= link_to setting, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <i class="fa fa-trash-o"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<h2><%= @setting.name %> Details</h2>
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="span6 offset3">
    <table class="table table-bordered">
      <tr>
        <th>Setting:</th>
        <td><%= @setting.name %></td>
      </tr>
      <tr>
        <th>Set:</th>
        <td><%= get_check(@setting.set) %></td>
      </tr>
      <tr>
        <th>Description:</th>
        <td><%= @setting.description %></td>
      </tr>
    </table>

    <%= link_to 'Edit', edit_setting_path(@setting) %> |
    <%= link_to 'Back', settings_path %>

  </div>
</div>