config/routes.rb
Mosh2::Application.routes.draw do
  resources :settings do
    put "toggle"
  end

  namespace :admin do
    resources :users
  end

  resources :poster_statuses

  resources :posters do
    put "finish", "pend", "print"
  end

  resources :job_statuses

  resources :jobs do
    put "finish", "pend", "finalize"
    resources :posters
  end

  resources :work_orders
  resources :order_statuses
  resources :after_hours_accesses
  resources :semesters
  resources :terms

  resources :locations do
    resources :workstations, only: [:index, :new, :create]
  end

  resources :location_types
  resources :hardwares, except: [:new, :create]
  resources :hardware_statuses
  resources :hardware_types

  resources :workstations, except: [:new, :create] do
    resources :hardwares, only: [:index, :new, :create]
  end

  resources :workstation_types
  resources :hours
  resources :lab_overview, only: :index
  resources :inventory, only: :index

  namespace :api do
    namespace :v1 do
      resources :labs, only: [:index, :show] do
        resources :workstations, only: :index
      end
      resources :workstations, only: :show do
        resources :hardwares, only: [:index, :new, :create]
      end
      resources :hardwares, only: :show
    end
  end

  devise_for :users

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root to: 'home#index'
end

app/controllers/location_types_controller.rb
class LocationTypesController < ApplicationController

require "#{Rails.root}/lib/mosh_modules/management_module"
include MoshModules::ManagementModule
before_filter :management_filter

  # GET /location_types
  # GET /location_types.json
  def index
    @location_types = LocationType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @location_types }
    end
  end

  # GET /location_types/1
  # GET /location_types/1.json
  def show
    @location_type = LocationType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location_type }
    end
  end

  # GET /location_types/new
  # GET /location_types/new.json
  def new
    @location_type = LocationType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location_type }
    end
  end

  # GET /location_types/1/edit
  def edit
    @location_type = LocationType.find(params[:id])
  end

  # POST /location_types
  # POST /location_types.json
  def create
    @location_type = LocationType.new(params[:location_type])

    respond_to do |format|
      if @location_type.save
        format.html { redirect_to @location_type, notice: 'Location type was successfully created.' }
        format.json { render json: @location_type, status: :created, location: @location_type }
      else
        format.html { render action: "new" }
        format.json { render json: @location_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /location_types/1
  # PUT /location_types/1.json
  def update
    @location_type = LocationType.find(params[:id])

    respond_to do |format|
      if @location_type.update_attributes(params[:location_type])
        format.html { redirect_to @location_type, notice: 'Location type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /location_types/1
  # DELETE /location_types/1.json
  def destroy
    @location_type = LocationType.find(params[:id])
    @location_type.destroy

    respond_to do |format|
      format.html { redirect_to location_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/location_types_helper.rb
module LocationTypesHelper
end

app/views/location_types/_form.html.erb
<%= simple_form_for(@location_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/location_types/edit.html.erb
<h1>Editing location_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @location_type %> |
<%= link_to 'Back', location_types_path %>

app/views/location_types/index.html.erb
<h1>Listing location_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @location_types.each do |location_type| %>
  <tr>
    <td><%= location_type.name %></td>
    <td><%= link_to 'Show', location_type %></td>
    <td><%= link_to 'Edit', edit_location_type_path(location_type) %></td>
    <td><%= link_to 'Destroy', location_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location type', new_location_type_path %>

app/views/location_types/new.html.erb
<h1>New location_type</h1>

<%= render 'form' %>

<%= link_to 'Back', location_types_path %>

app/views/location_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location_type.name %>
</p>


<%= link_to 'Edit', edit_location_type_path(@location_type) %> |
<%= link_to 'Back', location_types_path %>