config/routes.rb
Mosh2::Application.routes.draw do
  resources :settings do
    put "toggle"
  end

  namespace :admin do
    resources :users
  end

  resources :poster_statuses

  resources :posters do
    put "finish", "pend", "print"
  end

  resources :job_statuses

  resources :jobs do
    put "finish", "pend", "finalize"
    resources :posters
  end

  resources :work_orders
  resources :order_statuses
  resources :after_hours_accesses
  resources :semesters
  resources :terms

  resources :locations do
    resources :workstations, only: [:index, :new, :create]
  end

  resources :location_types
  resources :hardwares, except: [:new, :create]
  resources :hardware_statuses
  resources :hardware_types

  resources :workstations, except: [:new, :create] do
    resources :hardwares, only: [:index, :new, :create]
  end

  resources :workstation_types
  resources :hours
  resources :lab_overview, only: :index
  resources :inventory, only: :index

  namespace :api do
    namespace :v1 do
      resources :labs, only: [:index, :show] do
        resources :workstations, only: :index
      end
      resources :workstations, only: :show do
        resources :hardwares, only: [:index, :new, :create]
      end
      resources :hardwares, only: :show
    end
  end

  devise_for :users

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root to: 'home#index'
end

app/controllers/job_statuses_controller.rb
class JobStatusesController < ApplicationController
  # GET /job_statuses
  # GET /job_statuses.json
  def index
    @job_statuses = JobStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @job_statuses }
    end
  end

  # GET /job_statuses/1
  # GET /job_statuses/1.json
  def show
    @job_status = JobStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job_status }
    end
  end

  # GET /job_statuses/new
  # GET /job_statuses/new.json
  def new
    @job_status = JobStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job_status }
    end
  end

  # GET /job_statuses/1/edit
  def edit
    @job_status = JobStatus.find(params[:id])
  end

  # POST /job_statuses
  # POST /job_statuses.json
  def create
    @job_status = JobStatus.new(params[:job_status])

    respond_to do |format|
      if @job_status.save
        format.html { redirect_to @job_status, notice: 'Job status was successfully created.' }
        format.json { render json: @job_status, status: :created, location: @job_status }
      else
        format.html { render action: "new" }
        format.json { render json: @job_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /job_statuses/1
  # PUT /job_statuses/1.json
  def update
    @job_status = JobStatus.find(params[:id])

    respond_to do |format|
      if @job_status.update_attributes(params[:job_status])
        format.html { redirect_to @job_status, notice: 'Job status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_statuses/1
  # DELETE /job_statuses/1.json
  def destroy
    @job_status = JobStatus.find(params[:id])
    @job_status.destroy

    respond_to do |format|
      format.html { redirect_to job_statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/job_statuses_helper.rb
module JobStatusesHelper
end

app/views/job_statuses/_form.html.erb
<%= simple_form_for(@job_status) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/job_statuses/edit.html.erb
<h1>Editing job_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_status %> |
<%= link_to 'Back', job_statuses_path %>

app/views/job_statuses/index.html.erb
<h1>Listing job_statuses</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @job_statuses.each do |job_status| %>
  <tr>
    <td><%= job_status.name %></td>
    <td><%= link_to 'Show', job_status %></td>
    <td><%= link_to 'Edit', edit_job_status_path(job_status) %></td>
    <td><%= link_to 'Destroy', job_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Job status', new_job_status_path %>

app/views/job_statuses/new.html.erb
<h1>New job_status</h1>

<%= render 'form' %>

<%= link_to 'Back', job_statuses_path %>

app/views/job_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @job_status.name %>
</p>


<%= link_to 'Edit', edit_job_status_path(@job_status) %> |
<%= link_to 'Back', job_statuses_path %>